server:
  port: 8080

spring:
  profiles: docker
  jpa:
    showSql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  flyway:
    url: jdbc:postgresql://postgres:5432/mydb
logging:
  file:
    name: log/app.log